# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

language: r
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  exclude:
    - r: devel
      os: osx

sudo: false
cache: packages

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  on:
      os:     linux
      r:      release
      branch: master
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
