# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

language: r
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  exclude:
    - r: devel
      os: osx

sudo: false
cache: packages

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
